[project]
name = "imperial-robot-learning-rl"
version = "0.1.0"
description = "Robot RL project with Q-learning on Adeept Arm"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "opencv-python>=4.12.0.88",
    "serial>=0.0.97",
]
